function LSopts = lm_get_env_options(iEnv, LSopts)
% lm_get_env_options - Get and configure LINDO Environment Options
%
%   LSopts = lm_get_env_options(iEnv, LSopts) retrieves and configures
%   LINDO Environment options for a given LINDO environment (iEnv) and
%   stores them in the LSopts structure.
%
%   Input:
%   - iEnv: The LINDO environment handle.
%   - LSopts: The structure containing LINDO Environment options. This
%     structure could be previously initialized with default values.
%
%   Output:
%   - LSopts: The updated LSopts structure with LINDO Environment options.
%
%   Description:
%   This function is used to retrieve and configure various LINDO Environment
%   options associated with the specified LINDO environment. The input iEnv
%   should be a valid LINDO environment handle, and LSopts should be a
%   structure containing default option values. After calling this function,
%   LSopts will be populated with the actual option values retrieved from
%   the LINDO environment.
%
%   Example:
%   % Initialize an empty LSopts structure
%   LSopts = struct();
%
%   % Create a LINDO environment handle (iEnv) 
%   [iEnv, nErr] = mxlindo('LScreateEnv',...)
%
%   % Get and configure LINDO Environment options
%   LSopts = lm_get_env_options(iEnv, LSopts);
%
%   % LSopts now contains the configured LINDO Environment options
%
%   See also: lm_set_options
%
%   Author: MKA
%   Date: 2023-09-04

    lindo;
    % Initialize the LSopts structure
    if nargin<2,
        LSopts = struct();
    end
    verb = 1;

    % List of parameter names and corresponding macros
    paramNames = {
        'LS_IPARAM_OBJSENSE', 'OBJSENSE';
        'LS_IPARAM_CHECK_FOR_ERRORS', 'CHECK_FOR_ERRORS';
        'LS_IPARAM_ALLOW_CNTRLBREAK', 'ALLOW_CNTRLBREAK';
        'LS_IPARAM_DECOMPOSITION_TYPE', 'DECOMPOSITION_TYPE';
        'LS_IPARAM_BARRIER_SOLVER', 'BARRIER_SOLVER';
        'LS_IPARAM_MPS_OBJ_WRITESTYLE', 'MPS_OBJ_WRITESTYLE';
        'LS_IPARAM_SOL_REPORT_STYLE', 'SOL_REPORT_STYLE';
        'LS_IPARAM_INSTRUCT_LOADTYPE', 'INSTRUCT_LOADTYPE';
        'LS_IPARAM_STRING_LENLMT', 'STRING_LENLMT';
        'LS_IPARAM_USE_NAMEDATA', 'USE_NAMEDATA';
        'LS_IPARAM_COPY_MODE', 'COPY_MODE';
        'LS_IPARAM_SBD_NUM_THREADS', 'SBD_NUM_THREADS';
        'LS_IPARAM_NUM_THREADS', 'NUM_THREADS';
        'LS_IPARAM_MULTITHREAD_MODE', 'MULTITHREAD_MODE';
        'LS_IPARAM_FIND_BLOCK', 'FIND_BLOCK';
        'LS_IPARAM_PROFILER_LEVEL', 'PROFILER_LEVEL';
        'LS_IPARAM_INSTRUCT_READMODE', 'INSTRUCT_READMODE';
        'LS_IPARAM_INSTRUCT_SUBOUT', 'INSTRUCT_SUBOUT';
        'LS_IPARAM_SOLPOOL_LIM', 'SOLPOOL_LIM';
        'LS_IPARAM_FIND_SYMMETRY_LEVEL', 'FIND_SYMMETRY_LEVEL';
        'LS_IPARAM_FIND_SYMMETRY_PRINT_LEVEL', 'FIND_SYMMETRY_PRINT_LEVEL';
        'LS_IPARAM_TUNER_PRINT_LEVEL', 'TUNER_PRINT_LEVEL';
        'LS_IPARAM_DEFAULT_SEED', 'DEFAULT_SEED';
        'LS_IPARAM_XSOLVER_LOG_LEVEL', 'XSOLVER_LOG_LEVEL';
        'LS_IPARAM_SOLVER_IUSOL', 'SOLVER_IUSOL';
        'LS_IPARAM_SOLVER_TIMLMT', 'SOLVER_TIMLMT';
        'LS_IPARAM_SOLVER_RESTART', 'SOLVER_RESTART';
        'LS_IPARAM_SOLVER_IPMSOL', 'SOLVER_IPMSOL';
        'LS_IPARAM_SOLVER_USECUTOFFVAL', 'SOLVER_USECUTOFFVAL';
        'LS_IPARAM_SOLVER_PRE_ELIM_FILL', 'SOLVER_PRE_ELIM_FILL';
        'LS_IPARAM_SOLVER_CONCURRENT_OPTMODE', 'SOLVER_CONCURRENT_OPTMODE';
        'LS_IPARAM_SOLVER_PARTIALSOL_LEVEL', 'SOLVER_PARTIALSOL_LEVEL';
        'LS_IPARAM_SOLVER_MODE', 'SOLVER_MODE';
        'LS_IPARAM_SOLVER_METHOD', 'SOLVER_METHOD';
        'LS_IPARAM_SOLVER_DUALSOL', 'SOLVER_DUALSOL';
        'LS_IPARAM_LP_SCALE', 'LP_SCALE';
        'LS_IPARAM_LP_ITRLMT', 'LP_ITRLMT';
        'LS_IPARAM_SPLEX_PPRICING', 'SPLEX_PPRICING';
        'LS_IPARAM_SPLEX_REFACFRQ', 'SPLEX_REFACFRQ';
        'LS_IPARAM_PROB_TO_SOLVE', 'PROB_TO_SOLVE';
        'LS_IPARAM_LP_PRINTLEVEL', 'LP_PRINTLEVEL';
        'LS_IPARAM_SPLEX_DPRICING', 'SPLEX_DPRICING';
        'LS_IPARAM_SPLEX_DUAL_PHASE', 'SPLEX_DUAL_PHASE';
        'LS_IPARAM_LP_PRELEVEL', 'LP_PRELEVEL';
        'LS_IPARAM_SPLEX_USE_EXTERNAL', 'SPLEX_USE_EXTERNAL';
        'LS_IPARAM_LP_PPARTIAL', 'LP_PPARTIAL';
        'LS_IPARAM_LP_DPARTIAL', 'LP_DPARTIAL';
        'LS_IPARAM_LP_DRATIO', 'LP_DRATIO';
        'LS_IPARAM_LP_PRATIO', 'LP_PRATIO';
        'LS_IPARAM_LP_RATRANGE', 'LP_RATRANGE';
        'LS_IPARAM_LP_DPSWITCH', 'LP_DPSWITCH';
        'LS_IPARAM_LP_PALLOC', 'LP_PALLOC';
        'LS_IPARAM_LP_PRTFG', 'LP_PRTFG';
        'LS_IPARAM_LP_OPRFREE', 'LP_OPRFREE';
        'LS_IPARAM_LP_SPRINT_SUB', 'LP_SPRINT_SUB';
        'LS_IPARAM_LP_XMODE', 'LP_XMODE';
        'LS_IPARAM_LP_PCOLAL_FACTOR', 'LP_PCOLAL_FACTOR';
        'LS_IPARAM_LP_MAXMERGE', 'LP_MAXMERGE';
        'LS_IPARAM_LP_DYNOBJMODE', 'LP_DYNOBJMODE';
        'LS_IPARAM_LP_UMODE', 'LP_UMODE';
        'LS_IPARAM_LP_SPRINT_MAXPASS', 'LP_SPRINT_MAXPASS';
        'LS_IPARAM_LP_SPRINT_COLFACT', 'LP_SPRINT_COLFACT';
        'LS_IPARAM_LP_BASRECOV_METHOD', 'LP_BASRECOV_METHOD';
        'LS_IPARAM_LP_BASPOLISH_ITRLMT', 'LP_BASPOLISH_ITRLMT';
        'LS_IPARAM_LP_BASPOLISH_DEPTH', 'LP_BASPOLISH_DEPTH';
        'LS_IPARAM_LP_BASPOLISH_MODE', 'LP_BASPOLISH_MODE';
        'LS_IPARAM_LU_NUM_CANDITS', 'LU_NUM_CANDITS';
        'LS_IPARAM_LU_MAX_UPDATES', 'LU_MAX_UPDATES';
        'LS_IPARAM_LU_PRINT_LEVEL', 'LU_PRINT_LEVEL';
        'LS_IPARAM_LU_UPDATE_TYPE', 'LU_UPDATE_TYPE';
        'LS_IPARAM_LU_MODE', 'LU_MODE';
        'LS_IPARAM_LU_PIVMOD', 'LU_PIVMOD';
        'LS_IPARAM_LU_CORE', 'LU_CORE';
        'LS_IPARAM_IPM_MAX_ITERATIONS', 'IPM_MAX_ITERATIONS';
        'LS_IPARAM_IPM_OFF_COL_TRH', 'IPM_OFF_COL_TRH';
        'LS_IPARAM_IPM_NUM_THREADS', 'IPM_NUM_THREADS';
        'LS_IPARAM_IPM_CHECK_CONVEXITY', 'IPM_CHECK_CONVEXITY';
        'LS_IPARAM_NLP_SOLVE_AS_LP', 'NLP_SOLVE_AS_LP';
        'LS_IPARAM_NLP_SOLVER', 'NLP_SOLVER';
        'LS_IPARAM_NLP_SUBSOLVER', 'NLP_SUBSOLVER';
        'LS_IPARAM_NLP_PRINTLEVEL', 'NLP_PRINTLEVEL';
        'LS_IPARAM_NLP_DERIV_DIFFTYPE', 'NLP_DERIV_DIFFTYPE';
        'LS_IPARAM_NLP_USE_CRASH', 'NLP_USE_CRASH';
        'LS_IPARAM_NLP_USE_STEEPEDGE', 'NLP_USE_STEEPEDGE';
        'LS_IPARAM_NLP_USE_SLP', 'NLP_USE_SLP';
        'LS_IPARAM_NLP_USE_SELCONEVAL', 'NLP_USE_SELCONEVAL';
        'LS_IPARAM_NLP_PRELEVEL', 'NLP_PRELEVEL';
        'LS_IPARAM_NLP_ITRLMT', 'NLP_ITRLMT';
        'LS_IPARAM_NLP_LINEARZ', 'NLP_LINEARZ';
        'LS_IPARAM_NLP_LINEARITY', 'NLP_LINEARITY';
        'LS_IPARAM_NLP_STARTPOINT', 'NLP_STARTPOINT';
        'LS_IPARAM_NLP_CONVEXRELAX', 'NLP_CONVEXRELAX';
        'LS_IPARAM_NLP_CR_ALG_REFORM', 'NLP_CR_ALG_REFORM';
        'LS_IPARAM_NLP_QUADCHK', 'NLP_QUADCHK';
        'LS_IPARAM_NLP_AUTODERIV', 'NLP_AUTODERIV';
        'LS_IPARAM_NLP_MAXLOCALSEARCH', 'NLP_MAXLOCALSEARCH';
        'LS_IPARAM_NLP_CONVEX', 'NLP_CONVEX';
        'LS_IPARAM_NLP_CONOPT_VER', 'NLP_CONOPT_VER';
        'LS_IPARAM_NLP_USE_LINDO_CRASH', 'NLP_USE_LINDO_CRASH';
        'LS_IPARAM_NLP_STALL_ITRLMT', 'NLP_STALL_ITRLMT';
        'LS_IPARAM_NLP_AUTOHESS', 'NLP_AUTOHESS';
        'LS_IPARAM_NLP_FEASCHK', 'NLP_FEASCHK';
        'LS_IPARAM_NLP_MAXSUP', 'NLP_MAXSUP';
        'LS_IPARAM_NLP_MSW_SOLIDX', 'NLP_MSW_SOLIDX';
        'LS_IPARAM_NLP_ITERS_PER_LOGLINE', 'NLP_ITERS_PER_LOGLINE';
        'LS_IPARAM_NLP_MAX_RETRY', 'NLP_MAX_RETRY';
        'LS_IPARAM_NLP_MSW_NORM', 'NLP_MSW_NORM';
        'LS_IPARAM_NLP_MSW_POPSIZE', 'NLP_MSW_POPSIZE';
        'LS_IPARAM_NLP_MSW_MAXPOP', 'NLP_MSW_MAXPOP';
        'LS_IPARAM_NLP_MSW_MAXNOIMP', 'NLP_MSW_MAXNOIMP';
        'LS_IPARAM_NLP_MSW_FILTMODE', 'NLP_MSW_FILTMODE';
        'LS_IPARAM_NLP_MAXLOCALSEARCH_TREE', 'NLP_MAXLOCALSEARCH_TREE';
        'LS_IPARAM_NLP_MSW_NUM_THREADS', 'NLP_MSW_NUM_THREADS';
        'LS_IPARAM_NLP_MSW_RG_SEED', 'NLP_MSW_RG_SEED';
        'LS_IPARAM_NLP_MSW_PREPMODE', 'NLP_MSW_PREPMODE';
        'LS_IPARAM_NLP_MSW_RMAPMODE', 'NLP_MSW_RMAPMODE';
        'LS_IPARAM_NLP_XSMODE', 'NLP_XSMODE';
        'LS_IPARAM_NLP_IPM2GRG', 'NLP_IPM2GRG';
        'LS_IPARAM_NLP_USE_SDP', 'NLP_USE_SDP';
        'LS_IPARAM_NLP_LINEARZ_WB_CONSISTENT', 'NLP_LINEARZ_WB_CONSISTENT';
        'LS_IPARAM_NLP_USECUTOFFOBJ', 'NLP_USECUTOFFOBJ';
        'LS_IPARAM_NLP_CONIC_REFORM', 'NLP_CONIC_REFORM';
        'LS_IPARAM_NLP_QP_REFORM_LEVEL', 'NLP_QP_REFORM_LEVEL';
        'LS_IPARAM_MIP_TIMLIM', 'MIP_TIMLIM';
        'LS_IPARAM_MIP_AOPTTIMLIM', 'MIP_AOPTTIMLIM';
        'LS_IPARAM_MIP_LSOLTIMLIM', 'MIP_LSOLTIMLIM';
        'LS_IPARAM_MIP_PRELEVEL', 'MIP_PRELEVEL';
        'LS_IPARAM_MIP_NODESELRULE', 'MIP_NODESELRULE';
        'LS_IPARAM_MIP_MAXCUTPASS_TOP', 'MIP_MAXCUTPASS_TOP';
        'LS_IPARAM_MIP_MAXCUTPASS_TREE', 'MIP_MAXCUTPASS_TREE';
        'LS_IPARAM_MIP_MAXNONIMP_CUTPASS', 'MIP_MAXNONIMP_CUTPASS';
        'LS_IPARAM_MIP_CUTLEVEL_TOP', 'MIP_CUTLEVEL_TOP';
        'LS_IPARAM_MIP_CUTLEVEL_TREE', 'MIP_CUTLEVEL_TREE';
        'LS_IPARAM_MIP_CUTTIMLIM', 'MIP_CUTTIMLIM';
        'LS_IPARAM_MIP_CUTDEPTH', 'MIP_CUTDEPTH';
        'LS_IPARAM_MIP_CUTFREQ', 'MIP_CUTFREQ';
        'LS_IPARAM_MIP_HEULEVEL', 'MIP_HEULEVEL';
        'LS_IPARAM_MIP_PRINTLEVEL', 'MIP_PRINTLEVEL';
        'LS_IPARAM_MIP_PREPRINTLEVEL', 'MIP_PREPRINTLEVEL';
        'LS_IPARAM_MIP_USECUTOFFOBJ', 'MIP_USECUTOFFOBJ';
        'LS_IPARAM_MIP_STRONGBRANCHLEVEL', 'MIP_STRONGBRANCHLEVEL';
        'LS_IPARAM_MIP_TREEREORDERLEVEL', 'MIP_TREEREORDERLEVEL';
        'LS_IPARAM_MIP_BRANCHDIR', 'MIP_BRANCHDIR';
        'LS_IPARAM_MIP_TOPOPT', 'MIP_TOPOPT';
        'LS_IPARAM_MIP_REOPT', 'MIP_REOPT';
        'LS_IPARAM_MIP_SOLVERTYPE', 'MIP_SOLVERTYPE';
        'LS_IPARAM_MIP_KEEPINMEM', 'MIP_KEEPINMEM';
        'LS_IPARAM_MIP_BRANCHRULE', 'MIP_BRANCHRULE';
        'LS_IPARAM_MIP_HEUMINTIMLIM', 'MIP_HEUMINTIMLIM';
        'LS_IPARAM_MIP_BRANCH_PRIO', 'MIP_BRANCH_PRIO';
        'LS_IPARAM_MIP_SCALING_BOUND', 'MIP_SCALING_BOUND';
        'LS_IPARAM_MIP_DUAL_SOLUTION', 'MIP_DUAL_SOLUTION';
        'LS_IPARAM_MIP_BRANCH_LIMIT', 'MIP_BRANCH_LIMIT';
        'LS_IPARAM_MIP_AGGCUTLIM_TOP', 'MIP_AGGCUTLIM_TOP';
        'LS_IPARAM_MIP_AGGCUTLIM_TREE', 'MIP_AGGCUTLIM_TREE';
        'LS_IPARAM_MIP_ANODES_SWITCH_DF', 'MIP_ANODES_SWITCH_DF';
        'LS_IPARAM_MIP_PSEUDOCOST_RULE', 'MIP_PSEUDOCOST_RULE';
        'LS_IPARAM_MIP_ENUM_HEUMODE', 'MIP_ENUM_HEUMODE';
        'LS_IPARAM_MIP_PRELEVEL_TREE', 'MIP_PRELEVEL_TREE';
        'LS_IPARAM_MIP_USE_INT_ZERO_TOL', 'MIP_USE_INT_ZERO_TOL';
        'LS_IPARAM_MIP_USE_CUTS_HEU', 'MIP_USE_CUTS_HEU';
        'LS_IPARAM_MIP_STRONGBRANCHDONUM', 'MIP_STRONGBRANCHDONUM';
        'LS_IPARAM_MIP_MAKECUT_INACTIVE_COUNT', 'MIP_MAKECUT_INACTIVE_COUNT';
        'LS_IPARAM_MIP_PRE_ELIM_FILL', 'MIP_PRE_ELIM_FILL';
        'LS_IPARAM_MIP_HEU_MODE', 'MIP_HEU_MODE';
        'LS_IPARAM_MIP_FP_MODE', 'MIP_FP_MODE';
        'LS_IPARAM_MIP_FP_OPT_METHOD', 'MIP_FP_OPT_METHOD';
        'LS_IPARAM_MIP_FP_ITRLIM', 'MIP_FP_ITRLIM';
        'LS_IPARAM_MIP_FP_HEU_MODE', 'MIP_FP_HEU_MODE';
        'LS_IPARAM_MIP_LOCALBRANCHNUM', 'MIP_LOCALBRANCHNUM';
        'LS_IPARAM_MIP_MAXNUM_MIP_SOL_STORAGE', 'MIP_MAXNUM_MIP_SOL_STORAGE';
        'LS_IPARAM_MIP_CONCURRENT_TOPOPTMODE', 'MIP_CONCURRENT_TOPOPTMODE';
        'LS_IPARAM_MIP_CONCURRENT_REOPTMODE', 'MIP_CONCURRENT_REOPTMODE';
        'LS_IPARAM_MIP_PREHEU_LEVEL', 'MIP_PREHEU_LEVEL';
        'LS_IPARAM_MIP_PREHEU_PRE_LEVEL', 'MIP_PREHEU_PRE_LEVEL';
        'LS_IPARAM_MIP_PREHEU_PRINT_LEVEL', 'MIP_PREHEU_PRINT_LEVEL';
        'LS_IPARAM_MIP_PREHEU_TC_ITERLIM', 'MIP_PREHEU_TC_ITERLIM';
        'LS_IPARAM_MIP_PREHEU_DFE_VSTLIM', 'MIP_PREHEU_DFE_VSTLIM';
        'LS_IPARAM_MIP_PREHEU_VAR_SEQ', 'MIP_PREHEU_VAR_SEQ';
        'LS_IPARAM_MIP_USE_PARTIALSOL_LEVEL', 'MIP_USE_PARTIALSOL_LEVEL';
        'LS_IPARAM_MIP_GENERAL_MODE', 'MIP_GENERAL_MODE';
        'LS_IPARAM_MIP_NUM_THREADS', 'MIP_NUM_THREADS';
        'LS_IPARAM_MIP_POLISH_NUM_BRANCH_NEXT', 'MIP_POLISH_NUM_BRANCH_NEXT';
        'LS_IPARAM_MIP_POLISH_MAX_BRANCH_COUNT', 'MIP_POLISH_MAX_BRANCH_COUNT';
        'LS_IPARAM_MIP_CONCURRENT_STRATEGY', 'MIP_CONCURRENT_STRATEGY';
        'LS_IPARAM_MIP_BASCUTS_DONUM', 'MIP_BASCUTS_DONUM';
        'LS_IPARAM_MIP_PARA_SUB', 'MIP_PARA_SUB';
        'LS_IPARAM_MIP_PARA_ITR_MODE', 'MIP_PARA_ITR_MODE';
        'LS_IPARAM_MIP_PARA_FP', 'MIP_PARA_FP';
        'LS_IPARAM_MIP_PARA_FP_MODE', 'MIP_PARA_FP_MODE';
        'LS_IPARAM_MIP_HEU_DROP_OBJ', 'MIP_HEU_DROP_OBJ';
        'LS_IPARAM_MIP_PERSPECTIVE_REFORM', 'MIP_PERSPECTIVE_REFORM';
        'LS_IPARAM_MIP_TREEREORDERMODE', 'MIP_TREEREORDERMODE';
        'LS_IPARAM_MIP_XSOLVER', 'MIP_XSOLVER';
        'LS_IPARAM_MIP_BNB_TRY_BNP', 'MIP_BNB_TRY_BNP';
        'LS_IPARAM_MIP_KBEST_USE_GOP', 'MIP_KBEST_USE_GOP';
        'LS_IPARAM_MIP_SYMMETRY_MODE', 'MIP_SYMMETRY_MODE';
        'LS_IPARAM_MIP_ALLDIFF_METHOD', 'MIP_ALLDIFF_METHOD';
        'LS_IPARAM_MIP_SOLLIM', 'MIP_SOLLIM';
        'LS_IPARAM_MIP_FP_PROJECTION', 'MIP_FP_PROJECTION';
        'LS_IPARAM_MIP_SYMMETRY_NONZ', 'MIP_SYMMETRY_NONZ';
        'LS_IPARAM_MIP_FIXINIT_ITRLIM', 'MIP_FIXINIT_ITRLIM';
        'LS_IPARAM_GOP_TIMLIM', 'GOP_TIMLIM';
        'LS_IPARAM_GOP_OPTCHKMD', 'GOP_OPTCHKMD';
        'LS_IPARAM_GOP_BRANCHMD', 'GOP_BRANCHMD';
        'LS_IPARAM_GOP_MAXWIDMD', 'GOP_MAXWIDMD';
        'LS_IPARAM_GOP_PRELEVEL', 'GOP_PRELEVEL';
        'LS_IPARAM_GOP_POSTLEVEL', 'GOP_POSTLEVEL';
        'LS_IPARAM_GOP_BBSRCHMD', 'GOP_BBSRCHMD';
        'LS_IPARAM_GOP_DECOMPPTMD', 'GOP_DECOMPPTMD';
        'LS_IPARAM_GOP_ALGREFORMMD', 'GOP_ALGREFORMMD';
        'LS_IPARAM_GOP_RELBRNDMD', 'GOP_RELBRNDMD';
        'LS_IPARAM_GOP_PRINTLEVEL', 'GOP_PRINTLEVEL';
        'LS_IPARAM_GOP_BNDLIM_MODE', 'GOP_BNDLIM_MODE';
        'LS_IPARAM_GOP_BRANCH_LIMIT', 'GOP_BRANCH_LIMIT';
        'LS_IPARAM_GOP_CORELEVEL', 'GOP_CORELEVEL';
        'LS_IPARAM_GOP_OPT_MODE', 'GOP_OPT_MODE';
        'LS_IPARAM_GOP_HEU_MODE', 'GOP_HEU_MODE';
        'LS_IPARAM_GOP_SUBOUT_MODE', 'GOP_SUBOUT_MODE';
        'LS_IPARAM_GOP_USE_NLPSOLVE', 'GOP_USE_NLPSOLVE';
        'LS_IPARAM_GOP_LSOLBRANLIM', 'GOP_LSOLBRANLIM';
        'LS_IPARAM_GOP_LPSOPT', 'GOP_LPSOPT';
        'LS_IPARAM_GOP_QUADMD', 'GOP_QUADMD';
        'LS_IPARAM_GOP_LIM_MODE', 'GOP_LIM_MODE';
        'LS_IPARAM_GOP_LINEARZ', 'GOP_LINEARZ';
        'LS_IPARAM_GOP_NUM_THREADS', 'GOP_NUM_THREADS';
        'LS_IPARAM_GOP_MULTILINEAR', 'GOP_MULTILINEAR';
        'LS_IPARAM_GOP_QUAD_METHOD', 'GOP_QUAD_METHOD';
        'LS_IPARAM_GOP_SOLLIM', 'GOP_SOLLIM';
        'LS_IPARAM_GOP_CMINLP', 'GOP_CMINLP';
        'LS_IPARAM_GOP_CONIC_REFORM', 'GOP_CONIC_REFORM';
        'LS_IPARAM_LIC_CONSTRAINTS', 'LIC_CONSTRAINTS';
        'LS_IPARAM_LIC_VARIABLES', 'LIC_VARIABLES';
        'LS_IPARAM_LIC_INTEGERS', 'LIC_INTEGERS';
        'LS_IPARAM_LIC_NONLINEARVARS', 'LIC_NONLINEARVARS';
        'LS_IPARAM_LIC_GOP_INTEGERS', 'LIC_GOP_INTEGERS';
        'LS_IPARAM_LIC_GOP_NONLINEARVARS', 'LIC_GOP_NONLINEARVARS';
        'LS_IPARAM_LIC_DAYSTOEXP', 'LIC_DAYSTOEXP';
        'LS_IPARAM_LIC_DAYSTOTRIALEXP', 'LIC_DAYSTOTRIALEXP';
        'LS_IPARAM_LIC_NONLINEAR', 'LIC_NONLINEAR';
        'LS_IPARAM_LIC_EDUCATIONAL', 'LIC_EDUCATIONAL';
        'LS_IPARAM_LIC_RUNTIME', 'LIC_RUNTIME';
        'LS_IPARAM_LIC_NUMUSERS', 'LIC_NUMUSERS';
        'LS_IPARAM_LIC_BARRIER', 'LIC_BARRIER';
        'LS_IPARAM_LIC_GLOBAL', 'LIC_GLOBAL';
        'LS_IPARAM_LIC_PLATFORM', 'LIC_PLATFORM';
        'LS_IPARAM_LIC_MIP', 'LIC_MIP';
        'LS_IPARAM_LIC_SP', 'LIC_SP';
        'LS_IPARAM_LIC_CONIC', 'LIC_CONIC';
        'LS_IPARAM_LIC_RESERVED1', 'LIC_RESERVED1';
        'LS_IPARAM_IIS_ANALYZE_LEVEL', 'IIS_ANALYZE_LEVEL';
        'LS_IPARAM_IUS_ANALYZE_LEVEL', 'IUS_ANALYZE_LEVEL';
        'LS_IPARAM_IIS_TOPOPT', 'IIS_TOPOPT';
        'LS_IPARAM_IIS_REOPT', 'IIS_REOPT';
        'LS_IPARAM_IIS_USE_SFILTER', 'IIS_USE_SFILTER';
        'LS_IPARAM_IIS_PRINT_LEVEL', 'IIS_PRINT_LEVEL';
        'LS_IPARAM_IIS_INFEAS_NORM', 'IIS_INFEAS_NORM';
        'LS_IPARAM_IIS_ITER_LIMIT', 'IIS_ITER_LIMIT';
        'LS_IPARAM_IIS_TIME_LIMIT', 'IIS_TIME_LIMIT';
        'LS_IPARAM_IIS_METHOD', 'IIS_METHOD';
        'LS_IPARAM_IIS_USE_EFILTER', 'IIS_USE_EFILTER';
        'LS_IPARAM_IIS_USE_GOP', 'IIS_USE_GOP';
        'LS_IPARAM_IIS_NUM_THREADS', 'IIS_NUM_THREADS';
        'LS_IPARAM_IIS_GETMODE', 'IIS_GETMODE';
        'LS_IPARAM_FMT_ISSQL', 'FMT_ISSQL';
        'LS_IPARAM_STOC_NSAMPLE_SPAR', 'STOC_NSAMPLE_SPAR';
        'LS_IPARAM_STOC_NSAMPLE_STAGE', 'STOC_NSAMPLE_STAGE';
        'LS_IPARAM_STOC_RG_SEED', 'STOC_RG_SEED';
        'LS_IPARAM_STOC_METHOD', 'STOC_METHOD';
        'LS_IPARAM_STOC_REOPT', 'STOC_REOPT';
        'LS_IPARAM_STOC_TOPOPT', 'STOC_TOPOPT';
        'LS_IPARAM_STOC_ITER_LIM', 'STOC_ITER_LIM';
        'LS_IPARAM_STOC_PRINT_LEVEL', 'STOC_PRINT_LEVEL';
        'LS_IPARAM_STOC_DETEQ_TYPE', 'STOC_DETEQ_TYPE';
        'LS_IPARAM_STOC_CALC_EVPI', 'STOC_CALC_EVPI';
        'LS_IPARAM_STOC_SAMP_CONT_ONLY', 'STOC_SAMP_CONT_ONLY';
        'LS_IPARAM_STOC_BUCKET_SIZE', 'STOC_BUCKET_SIZE';
        'LS_IPARAM_STOC_MAX_NUMSCENS', 'STOC_MAX_NUMSCENS';
        'LS_IPARAM_STOC_SHARE_BEGSTAGE', 'STOC_SHARE_BEGSTAGE';
        'LS_IPARAM_STOC_NODELP_PRELEVEL', 'STOC_NODELP_PRELEVEL';
        'LS_IPARAM_STOC_DEBUG_MASK', 'STOC_DEBUG_MASK';
        'LS_IPARAM_STOC_VARCONTROL_METHOD', 'STOC_VARCONTROL_METHOD';
        'LS_IPARAM_STOC_CORRELATION_TYPE', 'STOC_CORRELATION_TYPE';
        'LS_IPARAM_STOC_WSBAS', 'STOC_WSBAS';
        'LS_IPARAM_STOC_ALD_OUTER_ITER_LIM', 'STOC_ALD_OUTER_ITER_LIM';
        'LS_IPARAM_STOC_ALD_INNER_ITER_LIM', 'STOC_ALD_INNER_ITER_LIM';
        'LS_IPARAM_CORE_ORDER_BY_STAGE', 'CORE_ORDER_BY_STAGE';
        'LS_IPARAM_STOC_MAP_MPI2LP', 'STOC_MAP_MPI2LP';
        'LS_IPARAM_STOC_AUTOAGGR', 'STOC_AUTOAGGR';
        'LS_IPARAM_STOC_BENCHMARK_SCEN', 'STOC_BENCHMARK_SCEN';
        'LS_IPARAM_STOC_ADD_MPI', 'STOC_ADD_MPI';
        'LS_IPARAM_STOC_ELIM_FXVAR', 'STOC_ELIM_FXVAR';
        'LS_IPARAM_STOC_SBD_OBJCUTFLAG', 'STOC_SBD_OBJCUTFLAG';
        'LS_IPARAM_STOC_SBD_NUMCANDID', 'STOC_SBD_NUMCANDID';
        'LS_IPARAM_STOC_NAMEDATA_LEVEL', 'STOC_NAMEDATA_LEVEL';
        'LS_IPARAM_STOC_SBD_MAXCUTS', 'STOC_SBD_MAXCUTS';
        'LS_IPARAM_STOC_DEQOPT', 'STOC_DEQOPT';
        'LS_IPARAM_STOC_DS_SUBFORM', 'STOC_DS_SUBFORM';
        'LS_IPARAM_STOC_NUM_THREADS', 'STOC_NUM_THREADS';
        'LS_IPARAM_STOC_DETEQ_NBLOCKS', 'STOC_DETEQ_NBLOCKS';
        'LS_IPARAM_SAMP_NCM_METHOD', 'SAMP_NCM_METHOD';
        'LS_IPARAM_SAMP_NCM_DSTORAGE', 'SAMP_NCM_DSTORAGE';
        'LS_IPARAM_SAMP_SCALE', 'SAMP_SCALE';
        'LS_IPARAM_SAMP_NCM_ITERLIM', 'SAMP_NCM_ITERLIM';
        'LS_IPARAM_SAMP_NUM_THREADS', 'SAMP_NUM_THREADS';
        'LS_IPARAM_SAMP_RG_BUFFER_SIZE', 'SAMP_RG_BUFFER_SIZE';
        'LS_IPARAM_BNP_LEVEL', 'BNP_LEVEL';
        'LS_IPARAM_BNP_PRINT_LEVEL', 'BNP_PRINT_LEVEL';
        'LS_IPARAM_BNP_NUM_THREADS', 'BNP_NUM_THREADS';
        'LS_IPARAM_BNP_FIND_BLK', 'BNP_FIND_BLK';
        'LS_IPARAM_BNP_PRELEVEL', 'BNP_PRELEVEL';
        'LS_IPARAM_BNP_BRANCH_LIMIT', 'BNP_BRANCH_LIMIT';
        'LS_IPARAM_GA_CXOVER_METHOD', 'GA_CXOVER_METHOD';
        'LS_IPARAM_GA_IXOVER_METHOD', 'GA_IXOVER_METHOD';
        'LS_IPARAM_GA_CMUTAT_METHOD', 'GA_CMUTAT_METHOD';
        'LS_IPARAM_GA_IMUTAT_METHOD', 'GA_IMUTAT_METHOD';
        'LS_IPARAM_GA_SEED', 'GA_SEED';
        'LS_IPARAM_GA_NGEN', 'GA_NGEN';
        'LS_IPARAM_GA_POPSIZE', 'GA_POPSIZE';
        'LS_IPARAM_GA_FILEOUT', 'GA_FILEOUT';
        'LS_IPARAM_GA_PRINTLEVEL', 'GA_PRINTLEVEL';
        'LS_IPARAM_GA_INJECT_OPT', 'GA_INJECT_OPT';
        'LS_IPARAM_GA_NUM_THREADS', 'GA_NUM_THREADS';
        'LS_IPARAM_GA_OBJDIR', 'GA_OBJDIR';
        'LS_IPARAM_GA_SSPACE', 'GA_SSPACE';
        'LS_IPARAM_VER_MAJOR', 'VER_MAJOR';
        'LS_IPARAM_VER_MINOR', 'VER_MINOR';
        'LS_IPARAM_VER_BUILD', 'VER_BUILD';
        'LS_IPARAM_VER_REVISION', 'VER_REVISION';
        'LS_IPARAM_VER_NUMBER', 'VER_NUMBER';
        % Add more parameter names and macros as needed
    };

    % Retrieve integer parameters
    for i = 1:size(paramNames, 1)
        macroName = paramNames{i, 1};
        paramName = paramNames{i, 2};
        try,
            [value, nErr] = mxlindo('LSgetEnvIntParameter', iEnv, eval(macroName));
            if nErr==0,
                if verb>0,
                    fprintf('LSopts.%s=%d .. ok.\n', paramName, value);
                end
                LSopts.(paramName) = value;
            else
                fprintf('Warning: cannot set LSopts.%s=%d, nErr=%d\n', paramName, value, nErr);
            end
        catch exception
            fprintf('Warning: cannot set LSopts.%s=%d, nErr=%d\n', paramName, value, nErr);
        end
            
    end

    % List of parameter names and corresponding macros for double parameters
    doubleParamNames = {
        'LS_DPARAM_CALLBACKFREQ', 'CALLBACKFREQ';
        'LS_DPARAM_OBJPRINTMUL', 'OBJPRINTMUL';
        'LS_DPARAM_SOLVER_CUTOFFVAL', 'SOLVER_CUTOFFVAL';
        'LS_DPARAM_SOLVER_FEASTOL', 'SOLVER_FEASTOL';
        'LS_DPARAM_SOLVER_OPTTOL', 'SOLVER_OPTTOL';
        'LS_DPARAM_SOLVER_TIMLMT', 'SOLVER_TIMLMT';
        'LS_DPARAM_SOLVER_PERT_FEASTOL', 'SOLVER_PERT_FEASTOL';
        'LS_DPARAM_LP_ITRLMT', 'LP_ITRLMT';
        'LS_DPARAM_LP_MIN_FEASTOL', 'LP_MIN_FEASTOL';
        'LS_DPARAM_LP_MAX_FEASTOL', 'LP_MAX_FEASTOL';
        'LS_DPARAM_LP_MIN_OPTTOL', 'LP_MIN_OPTTOL';
        'LS_DPARAM_LP_MAX_OPTTOL', 'LP_MAX_OPTTOL';
        'LS_DPARAM_LP_MIN_PIVTOL', 'LP_MIN_PIVTOL';
        'LS_DPARAM_LP_MAX_PIVTOL', 'LP_MAX_PIVTOL';
        'LS_DPARAM_LP_AIJ_ZEROTOL', 'LP_AIJ_ZEROTOL';
        'LS_DPARAM_LP_PIV_ZEROTOL', 'LP_PIV_ZEROTOL';
        'LS_DPARAM_LP_PIV_BIGTOL', 'LP_PIV_BIGTOL';
        'LS_DPARAM_LP_BIGM', 'LP_BIGM';
        'LS_DPARAM_LP_BNDINF', 'LP_BNDINF';
        'LS_DPARAM_LP_INFINITY', 'LP_INFINITY';
        'LS_DPARAM_LP_PERTFACT', 'LP_PERTFACT';
        'LS_DPARAM_LP_DYNOBJFACT', 'LP_DYNOBJFACT';
        'LS_DPARAM_LP_MERGEFACT', 'LP_MERGEFACT';
        'LS_DPARAM_LU_EPS_DIAG', 'LU_EPS_DIAG';
        'LS_DPARAM_LU_EPS_NONZ', 'LU_EPS_NONZ';
        'LS_DPARAM_LU_EPS_PIVABS', 'LU_EPS_PIVABS';
        'LS_DPARAM_LU_EPS_PIVREL', 'LU_EPS_PIVREL';
        'LS_DPARAM_LU_INI_RCOND', 'LU_INI_RCOND';
        'LS_DPARAM_LU_SPVTOL_UPDATE', 'LU_SPVTOL_UPDATE';
        'LS_DPARAM_LU_SPVTOL_FTRAN', 'LU_SPVTOL_FTRAN';
        'LS_DPARAM_LU_SPVTOL_BTRAN', 'LU_SPVTOL_BTRAN';
        'LS_DPARAM_IPM_TOL_INFEAS', 'IPM_TOL_INFEAS';
        'LS_DPARAM_IPM_TOL_PATH', 'IPM_TOL_PATH';
        'LS_DPARAM_IPM_TOL_PFEAS', 'IPM_TOL_PFEAS';
        'LS_DPARAM_IPM_TOL_REL_STEP', 'IPM_TOL_REL_STEP';
        'LS_DPARAM_IPM_TOL_PSAFE', 'IPM_TOL_PSAFE';
        'LS_DPARAM_IPM_TOL_DFEAS', 'IPM_TOL_DFEAS';
        'LS_DPARAM_IPM_TOL_DSAFE', 'IPM_TOL_DSAFE';
        'LS_DPARAM_IPM_TOL_MU_RED', 'IPM_TOL_MU_RED';
        'LS_DPARAM_IPM_BASIS_REL_TOL_S', 'IPM_BASIS_REL_TOL_S';
        'LS_DPARAM_IPM_BASIS_TOL_S', 'IPM_BASIS_TOL_S';
        'LS_DPARAM_IPM_BASIS_TOL_X', 'IPM_BASIS_TOL_X';
        'LS_DPARAM_IPM_BI_LU_TOL_REL_PIV', 'IPM_BI_LU_TOL_REL_PIV';
        'LS_DPARAM_IPM_CO_TOL_INFEAS', 'IPM_CO_TOL_INFEAS';
        'LS_DPARAM_IPM_CO_TOL_PFEAS', 'IPM_CO_TOL_PFEAS';
        'LS_DPARAM_IPM_CO_TOL_DFEAS', 'IPM_CO_TOL_DFEAS';
        'LS_DPARAM_IPM_CO_TOL_MU_RED', 'IPM_CO_TOL_MU_RED';
        'LS_DPARAM_NLP_PSTEP_FINITEDIFF', 'NLP_PSTEP_FINITEDIFF';
        'LS_DPARAM_NLP_FEASTOL', 'NLP_FEASTOL';
        'LS_DPARAM_NLP_REDGTOL', 'NLP_REDGTOL';
        'LS_DPARAM_NLP_ITRLMT', 'NLP_ITRLMT';
        'LS_DPARAM_NLP_MSW_POXDIST_THRES', 'NLP_MSW_POXDIST_THRES';
        'LS_DPARAM_NLP_MSW_EUCDIST_THRES', 'NLP_MSW_EUCDIST_THRES';
        'LS_DPARAM_NLP_MSW_XNULRAD_FACTOR', 'NLP_MSW_XNULRAD_FACTOR';
        'LS_DPARAM_NLP_MSW_XKKTRAD_FACTOR', 'NLP_MSW_XKKTRAD_FACTOR';
        'LS_DPARAM_NLP_MSW_OVERLAP_RATIO', 'NLP_MSW_OVERLAP_RATIO';
        'LS_DPARAM_NLP_INF', 'NLP_INF';
        'LS_DPARAM_NLP_CUTOFFOBJ', 'NLP_CUTOFFOBJ';
        'LS_DPARAM_MIP_INTTOL', 'MIP_INTTOL';
        'LS_DPARAM_MIP_RELINTTOL', 'MIP_RELINTTOL';
        'LS_DPARAM_MIP_RELOPTTOL', 'MIP_RELOPTTOL';
        'LS_DPARAM_MIP_PEROPTTOL', 'MIP_PEROPTTOL';
        'LS_DPARAM_MIP_ADDCUTPER', 'MIP_ADDCUTPER';
        'LS_DPARAM_MIP_ADDCUTPER_TREE', 'MIP_ADDCUTPER_TREE';
        'LS_DPARAM_MIP_CUTOFFOBJ', 'MIP_CUTOFFOBJ';
        'LS_DPARAM_MIP_REDCOSTFIX_CUTOFF', 'MIP_REDCOSTFIX_CUTOFF';
        'LS_DPARAM_MIP_ADDCUTOBJTOL', 'MIP_ADDCUTOBJTOL';
        'LS_DPARAM_MIP_PSEUDOCOST_WEIGT', 'MIP_PSEUDOCOST_WEIGT';
        'LS_DPARAM_MIP_LBIGM', 'MIP_LBIGM';
        'LS_DPARAM_MIP_DELTA', 'MIP_DELTA';
        'LS_DPARAM_MIP_ITRLIM', 'MIP_ITRLIM';
        'LS_DPARAM_MIP_SWITCHFAC_SIM_IPM_ITER', 'MIP_SWITCHFAC_SIM_IPM_ITER';
        'LS_DPARAM_MIP_ABSOPTTOL', 'MIP_ABSOPTTOL';
        'LS_DPARAM_MIP_MINABSOBJSTEP', 'MIP_MINABSOBJSTEP';
        'LS_DPARAM_MIP_REDCOSTFIX_CUTOFF_TREE', 'MIP_REDCOSTFIX_CUTOFF_TREE';
        'LS_DPARAM_MIP_BIGM_FOR_INTTOL', 'MIP_BIGM_FOR_INTTOL';
        'LS_DPARAM_MIP_TIMLIM', 'MIP_TIMLIM';
        'LS_DPARAM_MIP_AOPTTIMLIM', 'MIP_AOPTTIMLIM';
        'LS_DPARAM_MIP_LSOLTIMLIM', 'MIP_LSOLTIMLIM';
        'LS_DPARAM_MIP_CUTTIMLIM', 'MIP_CUTTIMLIM';
        'LS_DPARAM_MIP_HEUMINTIMLIM', 'MIP_HEUMINTIMLIM';
        'LS_DPARAM_MIP_FP_WEIGHT', 'MIP_FP_WEIGHT';
        'LS_DPARAM_MIP_FP_TIMLIM', 'MIP_FP_TIMLIM';
        'LS_DPARAM_MIP_OBJ_THRESHOLD', 'MIP_OBJ_THRESHOLD';
        'LS_DPARAM_MIP_SWITCHFAC_SIM_IPM_TIME', 'MIP_SWITCHFAC_SIM_IPM_TIME';
        'LS_DPARAM_MIP_ITRLIM_SIM', 'MIP_ITRLIM_SIM';
        'LS_DPARAM_MIP_ITRLIM_NLP', 'MIP_ITRLIM_NLP';
        'LS_DPARAM_MIP_ITRLIM_IPM', 'MIP_ITRLIM_IPM';
        'LS_DPARAM_MIP_POLISH_ALPHA_TARGET', 'MIP_POLISH_ALPHA_TARGET';
        'LS_DPARAM_MIP_BRANCH_TOP_VAL_DIFF_WEIGHT', 'MIP_BRANCH_TOP_VAL_DIFF_WEIGHT';
        'LS_DPARAM_MIP_PARA_RND_ITRLMT', 'MIP_PARA_RND_ITRLMT';
        'LS_DPARAM_MIP_PARA_INIT_NODE', 'MIP_PARA_INIT_NODE';
        'LS_DPARAM_MIP_ABSCUTTOL', 'MIP_ABSCUTTOL';
        'LS_DPARAM_GOP_RELOPTTOL', 'GOP_RELOPTTOL';
        'LS_DPARAM_GOP_FLTTOL', 'GOP_FLTTOL';
        'LS_DPARAM_GOP_BOXTOL', 'GOP_BOXTOL';
        'LS_DPARAM_GOP_WIDTOL', 'GOP_WIDTOL';
        'LS_DPARAM_GOP_DELTATOL', 'GOP_DELTATOL';
        'LS_DPARAM_GOP_BNDLIM', 'GOP_BNDLIM';
        'LS_DPARAM_GOP_TIMLIM', 'GOP_TIMLIM';
        'LS_DPARAM_GOP_BRANCH_LIMIT', 'GOP_BRANCH_LIMIT';
        'LS_DPARAM_GOP_ITRLIM', 'GOP_ITRLIM';
        'LS_DPARAM_GOP_ITRLIM_SIM', 'GOP_ITRLIM_SIM';
        'LS_DPARAM_GOP_ITRLIM_IPM', 'GOP_ITRLIM_IPM';
        'LS_DPARAM_GOP_ITRLIM_NLP', 'GOP_ITRLIM_NLP';
        'LS_DPARAM_GOP_ABSOPTTOL', 'GOP_ABSOPTTOL';
        'LS_DPARAM_GOP_PEROPTTOL', 'GOP_PEROPTTOL';
        'LS_DPARAM_GOP_AOPTTIMLIM', 'GOP_AOPTTIMLIM';
        'LS_DPARAM_GOP_OBJ_THRESHOLD', 'GOP_OBJ_THRESHOLD';
        'LS_DPARAM_IIS_ITER_LIMIT', 'IIS_ITER_LIMIT';
        'LS_DPARAM_STOC_TIME_LIM', 'STOC_TIME_LIM';
        'LS_DPARAM_STOC_RELOPTTOL', 'STOC_RELOPTTOL';
        'LS_DPARAM_STOC_ABSOPTTOL', 'STOC_ABSOPTTOL';
        'LS_DPARAM_STOC_ALD_DUAL_FEASTOL', 'STOC_ALD_DUAL_FEASTOL';
        'LS_DPARAM_STOC_ALD_PRIMAL_FEASTOL', 'STOC_ALD_PRIMAL_FEASTOL';
        'LS_DPARAM_STOC_ALD_DUAL_STEPLEN', 'STOC_ALD_DUAL_STEPLEN';
        'LS_DPARAM_STOC_ALD_PRIMAL_STEPLEN', 'STOC_ALD_PRIMAL_STEPLEN';
        'LS_DPARAM_STOC_INFBND', 'STOC_INFBND';
        'LS_DPARAM_STOC_SBD_OBJCUTVAL', 'STOC_SBD_OBJCUTVAL';
        'LS_DPARAM_STOC_BIGM', 'STOC_BIGM';
        'LS_DPARAM_STOC_REL_PSTEPTOL', 'STOC_REL_PSTEPTOL';
        'LS_DPARAM_STOC_REL_DSTEPTOL', 'STOC_REL_DSTEPTOL';
        'LS_DPARAM_SAMP_NCM_CUTOBJ', 'SAMP_NCM_CUTOBJ';
        'LS_DPARAM_SAMP_CDSINC', 'SAMP_CDSINC';
        'LS_DPARAM_SAMP_NCM_OPTTOL', 'SAMP_NCM_OPTTOL';
        'LS_DPARAM_BNP_INFBND', 'BNP_INFBND';
        'LS_DPARAM_BNP_BOX_SIZE', 'BNP_BOX_SIZE';
        'LS_DPARAM_BNP_SUB_ITRLMT', 'BNP_SUB_ITRLMT';
        'LS_DPARAM_BNP_COL_LMT', 'BNP_COL_LMT';
        'LS_DPARAM_BNP_TIMLIM', 'BNP_TIMLIM';
        'LS_DPARAM_BNP_ITRLIM_SIM', 'BNP_ITRLIM_SIM';
        'LS_DPARAM_BNP_ITRLIM_IPM', 'BNP_ITRLIM_IPM';
        'LS_DPARAM_BNP_ITRLIM', 'BNP_ITRLIM';
        'LS_DPARAM_GA_CXOVER_PROB', 'GA_CXOVER_PROB';
        'LS_DPARAM_GA_XOVER_SPREAD', 'GA_XOVER_SPREAD';
        'LS_DPARAM_GA_IXOVER_PROB', 'GA_IXOVER_PROB';
        'LS_DPARAM_GA_CMUTAT_PROB', 'GA_CMUTAT_PROB';
        'LS_DPARAM_GA_MUTAT_SPREAD', 'GA_MUTAT_SPREAD';
        'LS_DPARAM_GA_IMUTAT_PROB', 'GA_IMUTAT_PROB';
        'LS_DPARAM_GA_TOL_ZERO', 'GA_TOL_ZERO';
        'LS_DPARAM_GA_TOL_PFEAS', 'GA_TOL_PFEAS';
        'LS_DPARAM_GA_INF', 'GA_INF';
        'LS_DPARAM_GA_INFBND', 'GA_INFBND';
        'LS_DPARAM_GA_BLXA', 'GA_BLXA';
        'LS_DPARAM_GA_BLXB', 'GA_BLXB';
        'LS_DPARAM_GA_OBJSTOP', 'GA_OBJSTOP';
        'LS_DPARAM_GA_MIGRATE_PROB', 'GA_MIGRATE_PROB';
        % Add more double parameter names and macros as needed
    };

    % Retrieve double parameters
    for i = 1:size(doubleParamNames, 1)
        macroName = doubleParamNames{i, 1};
        paramName = doubleParamNames{i, 2};
        try,
            [value, nErr] = mxlindo('LSgetEnvDouParameter', iEnv, eval(macroName));
            if nErr==0,
                if verb>0,
                    fprintf('LSopts.%s=%d .. ok.\n', paramName, value);
                end
                LSopts.(paramName) = value;
            else
                fprintf('Warning: cannot set LSopts.%s=%d, nErr=%d\n', paramName, value, nErr);
            end
        catch exception
            fprintf('Warning: cannot set LSopts.%s=%d, nErr=%d\n', paramName, value, nErr);
        end
    end
end